options:
  logging: CLOUD_LOGGING_ONLY  # or use NONE to disable logging
steps:
  - name: 'docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops', '.']
images:
  - 'gcr.io/$PROJECT_ID/gcpdevops'
