name: Build and push application to GKE
on:
 push:
   branches:
     - main
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: checkout repo
       uses: actions/checkout@v2 
     - name: login into GKE
       uses: 

